# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Sample1.py
# Created on: 2013-08-20 10:56:59.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
import arceditor


# Import arcpy module
import arcpy


# Local variables:
gisowner_Naperville_sde = "C:\\Student\\CMGD\\GDBMaintenance\\gisowner@Naperville.sde"

# Process: Analyze Datasets
arcpy.AnalyzeDatasets_management(gisowner_Naperville_sde, "NO_SYSTEM", "", "ANALYZE_BASE", "ANALYZE_DELTA", "ANALYZE_ARCHIVE")

